services:
- type: web
  name: resolver-ia-backend
  runtime: docker
  repo: https://github.com/TheCousinMate/resolver-ia-backend
  plan: starter
  envVars:
  - key: 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
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
version: "1"
