# render.yaml — generado el 18 mayo 2025
services:
  - type: web
    name: resolver-ia-backend
    runtime: docker
    repo: https://github.com/TheCousinMate/resolver-ia-backend
    plan: starter
    region: oregon
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    envVars:
      - key: PORT
        value: 10000
      - key: HUGGINGFACE_TOKEN
        sync: false
      - key: API_BASE_URL
        sync: false
      - key: PLAN_NAME
        sync: false
      - key: ACCOUNT_EMAIL
        sync: false
